# Generated by Django 4.1.5 on 2023-01-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poject',
            new_name='Project',
        ),
    ]
